import type { Lang } from "./i18n";

/* Informazioni di contatto — punto unico di verità */
export const info = {
  brand: "Alo Alo Pua Poke",
  tagline: { it: "Poke bar hawaiano · Bologna", en: "Hawaiian poke bar · Bologna" },
  address: "Via Filippo Schiassi, 32/a",
  city: "40138 Bologna (BO)",
  phone: "+39 051 007 3289",
  phoneHref: "tel:+390510073289",
  email: "aloalopuapoke@gmail.com",
  company: "ORDINE 33 S.R.L.",
  vat: "04382121202",
  maps: "https://maps.google.com/?q=Via+Filippo+Schiassi+32a+Bologna",
  hours: {
    it: [
      { d: "Lun – Sab", h: "11:30 – 15:00 · 18:30 – 22:00" },
      { d: "Domenica", h: "Chiuso" },
    ],
    en: [
      { d: "Mon – Sat", h: "11:30 – 15:00 · 18:30 – 22:00" },
      { d: "Sunday", h: "Closed" },
    ],
  },
  social: {
    instagram: "https://www.instagram.com/aloalopuapoke/",
    facebook: "https://www.facebook.com/aloalopuapoke/",
    google: "https://www.google.com/search?q=Alo+Alo+Pua+Poke+Bologna",
    tripadvisor: "https://www.tripadvisor.it/",
    justeat: "https://www.justeat.it/",
  },
  family: "Mestizo Lab",
  familyUrl: "https://mestizo-lab.com",
};

const it = {
  nav: {
    home: "Home",
    menu: "Menù",
    about: "About",
    contact: "Contatti",
    app: "AloAlo App",
    order: "Ordina ora",
  },
  announce: "Scarica l’AloAlo App e ottieni il 10% sul primo ordine →",
  reopen: "Riapertura il 31 agosto · Locale in fase di rinnovamento",
  hero: {
    eyebrow: "Poke bar hawaiano · Bologna",
    titleTop: "L’Hawaiian taste",
    titleBottom: "a Bologna",
    lead: "Bowl colorate, pesce marinato ogni giorno e salse fatte in casa. Un angolo di Hawaii nel cuore di Bologna — da mangiare qui o in delivery.",
    ctaMenu: "Scopri il menù",
    ctaOrder: "Ordina ora",
    caption: "Locale in Via Filippo Schiassi 32/a — immagini dei nostri piatti e del nostro angolo tropicale.",
  },
  worlds: {
    eyebrow: "Non solo poke",
    title: "La cucina hawaiana è un viaggio",
    lead: "Il poke è solo l’inizio. Ogni preparazione nasce da ingredienti freschi, marinature curate e un tocco tropicale.",
    items: [
      { name: "Poke Bowl", desc: "Base a scelta, pesce marinato, topping croccanti e le nostre salse." },
      { name: "Avotoast", desc: "Pane d’oro tostato, avocado cremoso e condimenti di mare o di terra." },
      { name: "Tartare & Ceviche", desc: "Tonno e gambero crudi, agrumi e spezie: freschezza allo stato puro." },
      { name: "Tapas & Bowl", desc: "Guacamole, hummus, alga wakame e fruit bowl per ogni momento." },
    ],
  },
  signature: {
    eyebrow: "Le nostre proposte",
    title: "Quattro poke firmati",
    lead: "Ricette d’autore già bilanciate. Oppure creale tu, passo dopo passo.",
    builderCta: "Crea il tuo poke",
  },
  ambiente: {
    eyebrow: "Il locale",
    title: "Un’isola verde in città",
    lead: "Sedute tra piante, luci calde e legno naturale. Alo Alo è pensato per una pausa pranzo veloce o una cena leggera in compagnia.",
    cta: "Scopri l’ambiente",
  },
  artigiani: {
    eyebrow: "Fatto in casa",
    title: "Salse artigianali, zero conservanti",
    lead: "Tutte le salse che accompagnano le nostre poke sono prodotte artigianalmente, senza conservanti. Tante opzioni vegane e gluten free, perché il gusto sia di tutti.",
    points: [
      { t: "Pesce fresco", d: "Marinato ogni giorno in laboratorio." },
      { t: "Vegano & gluten free", d: "Basi, proteine e salse per ogni esigenza." },
      { t: "Packaging green", d: "Bowl compostabili, anche in delivery." },
    ],
  },
  app: {
    eyebrow: "AloAlo App",
    title: "Ordina in un tap, con il 10% di sconto",
    lead: "Scarica l’app AloAlo: accumuli punti, salti la fila e ricevi il 10% di sconto sul tuo primo ordine.",
    ios: "App Store",
    android: "Google Play",
    perk: "-10% sul primo ordine",
  },
  reviews: {
    eyebrow: "Dicono di noi",
    title: "Ci trovi anche qui",
    lead: "Leggi le recensioni e ordina dalle piattaforme che preferisci.",
  },
  finalCta: {
    title: "Fame di Hawaii?",
    lead: "Passa a trovarci in Via Filippo Schiassi o ricevi la tua bowl a casa.",
    ctaOrder: "Ordina ora",
    ctaMap: "Come raggiungerci",
  },
  footer: {
    tagline: "Poke bar hawaiano nel cuore di Bologna. Fresco, colorato, fatto in casa.",
    nav: "Naviga",
    contact: "Contatti",
    follow: "Seguici",
    family: "Parte della famiglia",
    rights: "Tutti i diritti riservati.",
    hoursLabel: "Orari",
    privacy: "Privacy & Cookie",
    cookiePrefs: "Preferenze cookie",
  },
  cookie: {
    text: "Questo sito Web utilizza i cookie per garantire la migliore esperienza possibile.",
    more: "Ulteriori informazioni…",
    reject: "Rifiuta",
    accept: "Accetta",
  },
  newsletter: {
    eyebrow: "Lōkahi",
    title: "Lōkahi",
    subtitle: "in hawaiano vuol dire unità e armonia",
    lead: "Entra nel Club Alo Alo: sarai il primo a scoprire novità e offerte speciali. E ti regaliamo il 10% sul prossimo ordine.",
    namePlaceholder: "Il tuo nome",
    emailPlaceholder: "La tua email",
    cta: "Iscriviti",
    success: "Benvenuto nel Lōkahi! Controlla la tua email.",
    error: "Inserisci un’email valida.",
    privacy: "Iscrivendoti accetti la privacy policy. Niente spam, promesso.",
  },
  menuPage: {
    eyebrow: "Menù",
    title: "Il nostro menù",
    lead: "Poke firmati o creati da te, avotoast, tartare, tapas e dolci fatti in casa. Per allergie e intolleranze, chiedi pure a noi.",
    regular: "Regular",
    large: "Large",
    from: "da",
    allergens: "Per allergie e intolleranze chiedi al nostro staff: sapremo consigliarti.",
    builderTitle: "Componi il tuo poke",
    builderLead: "Scegli la taglia — Regular, Large o XL — e sei passaggi per la bowl perfetta.",
    priceAsk: "prezzo in cassa",
    novelty: "Novità",
  },
  aboutPage: {
    eyebrow: "About us",
    title: "Alo Alo, l’Hawaii a Bologna",
    lead: "Nasce dall’idea di portare a Bologna il gusto fresco e colorato della cucina hawaiana, con la cura di un laboratorio artigianale.",
    story1:
      "Alo Alo Pua Poke è un poke bar dove il pesce viene marinato ogni giorno, le salse sono fatte in casa e ogni bowl è un piccolo viaggio tra oceano e terra. Niente conservanti, tanta freschezza e opzioni per tutti: vegane, gluten free e senza rinunciare al gusto.",
    story2:
      "Facciamo parte della famiglia Mestizo Lab, il laboratorio di cucine del mondo che unisce sapori lontani sotto lo stesso tetto. Da noi trovi un ambiente verde e rilassato, perfetto per una pausa veloce o una cena leggera.",
    valuesTitle: "Cosa ci muove",
    values: [
      { t: "Freschezza vera", d: "Ingredienti selezionati e pesce marinato in giornata." },
      { t: "Fatto a mano", d: "Salse e preparazioni artigianali, senza conservanti." },
      { t: "Per tutti", d: "Scelte vegane e gluten free in ogni categoria." },
      { t: "Sostenibile", d: "Packaging compostabile, anche in delivery." },
    ],
  },
  contactPage: {
    eyebrow: "Contatti",
    title: "Vieni a trovarci",
    lead: "Siamo in Via Filippo Schiassi 32/a a Bologna, a due passi dal Sant’Orsola. Passa a trovarci, chiamaci o ordina in delivery.",
    addressLabel: "Indirizzo",
    hoursLabel: "Orari",
    phoneLabel: "Telefono",
    emailLabel: "Email",
    directions: "Apri in Google Maps",
    orderTitle: "Ordina in delivery",
    orderLead: "Ricevi la tua bowl a casa dalle piattaforme partner o dall’AloAlo App.",
  },
  appPage: {
    eyebrow: "AloAlo App",
    title: "Tutta Alo Alo nel tuo telefono",
    lead: "Ordina, accumula punti e ricevi vantaggi dedicati. Il primo ordine è scontato del 10%.",
    features: [
      { t: "-10% al primo ordine", d: "Il tuo benvenuto nella famiglia AloAlo." },
      { t: "Ordine express", d: "Componi la tua poke e salta la fila." },
      { t: "Punti e premi", d: "Ogni ordine ti avvicina a un premio." },
      { t: "Offerte solo app", d: "Promo riservate a chi usa l’app." },
    ],
    download: "Scarica l’app",
    ios: "App Store",
    android: "Google Play",
    note: "Disponibile per iOS e Android.",
  },
  common: {
    langLabel: "EN",
    langFull: "English",
    backHome: "Torna alla home",
    illustrative: "Immagine indicativa: la presentazione reale può variare.",
    menuFull: "Vedi il menù completo",
  },
};

const en: typeof it = {
  nav: {
    home: "Home",
    menu: "Menu",
    about: "About",
    contact: "Contact",
    app: "AloAlo App",
    order: "Order now",
  },
  announce: "Download the AloAlo App and get 10% off your first order →",
  reopen: "Reopening August 31 · Venue under renovation",
  hero: {
    eyebrow: "Hawaiian poke bar · Bologna",
    titleTop: "The Hawaiian taste",
    titleBottom: "in Bologna",
    lead: "Colourful bowls, fish marinated fresh every day and homemade sauces. A slice of Hawaii in the heart of Bologna — dine in or delivered.",
    ctaMenu: "See the menu",
    ctaOrder: "Order now",
    caption: "Located at Via Filippo Schiassi 32/a — images of our dishes and our tropical corner.",
  },
  worlds: {
    eyebrow: "Beyond poke",
    title: "Hawaiian food is a journey",
    lead: "Poke is only the start. Every dish is built on fresh ingredients, careful marinades and a tropical touch.",
    items: [
      { name: "Poke Bowl", desc: "Your base, marinated fish, crunchy toppings and our sauces." },
      { name: "Avotoast", desc: "Toasted golden bread, creamy avocado and sea or land toppings." },
      { name: "Tartare & Ceviche", desc: "Raw tuna and prawn, citrus and spice: pure freshness." },
      { name: "Tapas & Bowl", desc: "Guacamole, hummus, wakame and fruit bowl for any moment." },
    ],
  },
  signature: {
    eyebrow: "Our signatures",
    title: "Four signature pokes",
    lead: "Chef-balanced recipes. Or build your own, step by step.",
    builderCta: "Build your poke",
  },
  ambiente: {
    eyebrow: "The venue",
    title: "A green island in the city",
    lead: "Seats among plants, warm lights and natural wood. Alo Alo is made for a quick lunch break or a light dinner with friends.",
    cta: "See the space",
  },
  artigiani: {
    eyebrow: "Homemade",
    title: "Artisan sauces, zero preservatives",
    lead: "Every sauce we serve with our pokes is made in-house, with no preservatives. Plenty of vegan and gluten-free options, so taste is for everyone.",
    points: [
      { t: "Fresh fish", d: "Marinated daily in our kitchen." },
      { t: "Vegan & gluten free", d: "Bases, proteins and sauces for every need." },
      { t: "Green packaging", d: "Compostable bowls, delivery included." },
    ],
  },
  app: {
    eyebrow: "AloAlo App",
    title: "Order in a tap, with 10% off",
    lead: "Download the AloAlo app: collect points, skip the queue and get 10% off your first order.",
    ios: "App Store",
    android: "Google Play",
    perk: "-10% on your first order",
  },
  reviews: {
    eyebrow: "People say",
    title: "Find us here too",
    lead: "Read the reviews and order from your favourite platform.",
  },
  finalCta: {
    title: "Craving Hawaii?",
    lead: "Drop by in Via Filippo Schiassi or get your bowl delivered home.",
    ctaOrder: "Order now",
    ctaMap: "Get directions",
  },
  footer: {
    tagline: "Hawaiian poke bar in the heart of Bologna. Fresh, colourful, homemade.",
    nav: "Explore",
    contact: "Contact",
    follow: "Follow us",
    family: "Part of the family",
    rights: "All rights reserved.",
    hoursLabel: "Hours",
    privacy: "Privacy & Cookie",
    cookiePrefs: "Cookie preferences",
  },
  cookie: {
    text: "This website uses cookies to ensure the best possible experience.",
    more: "Learn more…",
    reject: "Decline",
    accept: "Accept",
  },
  newsletter: {
    eyebrow: "Lōkahi",
    title: "Lōkahi",
    subtitle: "is Hawaiian for unity and harmony",
    lead: "Join the Alo Alo Club: be the first to hear about news and special offers. Plus 10% off your next order.",
    namePlaceholder: "Your name",
    emailPlaceholder: "Your email",
    cta: "Sign up",
    success: "Welcome to the Lōkahi! Check your inbox.",
    error: "Please enter a valid email.",
    privacy: "By signing up you accept our privacy policy. No spam, promise.",
  },
  menuPage: {
    eyebrow: "Menu",
    title: "Our menu",
    lead: "Signature or build-your-own pokes, avotoast, tartare, tapas and homemade desserts. For allergies and intolerances, just ask us.",
    regular: "Regular",
    large: "Large",
    from: "from",
    allergens: "For allergies and intolerances ask our staff: we’ll be glad to help.",
    builderTitle: "Build your poke",
    builderLead: "Pick a size — Regular, Large or XL — and six steps to the perfect bowl.",
    priceAsk: "ask in store",
    novelty: "New",
  },
  aboutPage: {
    eyebrow: "About us",
    title: "Alo Alo, Hawaii in Bologna",
    lead: "Born from the idea of bringing the fresh, colourful taste of Hawaiian food to Bologna, with the care of an artisan kitchen.",
    story1:
      "Alo Alo Pua Poke is a poke bar where fish is marinated every day, sauces are homemade and every bowl is a little journey between ocean and land. No preservatives, lots of freshness and options for everyone: vegan, gluten free and never short on flavour.",
    story2:
      "We’re part of the Mestizo Lab family, the world-cuisine kitchen that brings distant flavours under one roof. Here you’ll find a green, relaxed space, perfect for a quick break or a light dinner.",
    valuesTitle: "What drives us",
    values: [
      { t: "Real freshness", d: "Selected ingredients and fish marinated same-day." },
      { t: "Handmade", d: "Artisan sauces and prep, no preservatives." },
      { t: "For everyone", d: "Vegan and gluten-free choices in every category." },
      { t: "Sustainable", d: "Compostable packaging, delivery included." },
    ],
  },
  contactPage: {
    eyebrow: "Contact",
    title: "Come and see us",
    lead: "We’re at Via Filippo Schiassi 32/a in Bologna, steps from Sant’Orsola. Come by, call us or order for delivery.",
    addressLabel: "Address",
    hoursLabel: "Hours",
    phoneLabel: "Phone",
    emailLabel: "Email",
    directions: "Open in Google Maps",
    orderTitle: "Order for delivery",
    orderLead: "Get your bowl delivered from our partner platforms or the AloAlo App.",
  },
  appPage: {
    eyebrow: "AloAlo App",
    title: "All of Alo Alo in your phone",
    lead: "Order, collect points and unlock dedicated perks. Your first order is 10% off.",
    features: [
      { t: "-10% first order", d: "Your welcome into the AloAlo family." },
      { t: "Express ordering", d: "Build your poke and skip the queue." },
      { t: "Points & rewards", d: "Every order brings you closer to a reward." },
      { t: "App-only deals", d: "Promos reserved for app users." },
    ],
    download: "Download the app",
    ios: "App Store",
    android: "Google Play",
    note: "Available for iOS and Android.",
  },
  common: {
    langLabel: "IT",
    langFull: "Italiano",
    backHome: "Back to home",
    illustrative: "Illustrative image: the actual dish may vary.",
    menuFull: "See the full menu",
  },
};

export const content: Record<Lang, typeof it> = { it, en };
export type SiteContent = typeof it;
